project_id = "nzxgcfwranspxynzyglb"

[api]
enabled = true
schemas = ["public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "http://localhost:8080"
additional_redirect_urls = ["https://orderfit-omega.vercel.app"]

[storage]
enabled = true
