const itemDetails = {
  '양파': { category:'채소', zone:'주방', stock:'16kg', minimum:'8kg', vendor:'푸른식자재', unit:'kg', total:'₩384,000', count:'12건', avg:'₩1,600/kg', recent:'₩1,520/kg', rows:[['2026.08.08','푸른식자재','20kg','₩1,520','₩30,400'],['2026.08.01','푸른식자재','20kg','₩1,680','₩33,600'],['2026.07.25','산들농산','15kg','₩1,600','₩24,000']] },
  '한우 등심': { category:'육류', zone:'주방', stock:'7kg', minimum:'5kg', vendor:'한성정육', unit:'kg', total:'₩1,250,000', count:'12건', avg:'₩42,000/kg', recent:'₩47,000/kg', rows:[['2026.08.07','한성정육','5kg','₩47,000','₩235,000'],['2026.07.30','한성정육','8kg','₩43,000','₩344,000'],['2026.07.18','미트월드','4kg','₩41,000','₩164,000']] },
  '식용유': { category:'소스·유지', zone:'주방', stock:'22L', minimum:'18L', vendor:'그린패키지', unit:'L', total:'₩171,000', count:'6건', avg:'₩2,880/L', recent:'₩2,850/L', rows:[['2026.08.05','그린패키지','18L','₩2,850','₩51,300'],['2026.07.14','그린패키지','18L','₩2,920','₩52,560'],['2026.06.27','푸른식자재','18L','₩2,870','₩51,660']] },
  '포장용기': { category:'소모품', zone:'홀', stock:'420개', minimum:'300개', vendor:'그린패키지', unit:'개', total:'₩154,800', count:'5건', avg:'₩172/개', recent:'₩180/개', rows:[['2026.08.05','그린패키지','500개','₩180','₩90,000'],['2026.07.03','그린패키지','300개','₩165','₩49,500'],['2026.06.02','패키지온','100개','₩153','₩15,300']] },
  '냅킨': { category:'소모품', zone:'홀', stock:'6박스', minimum:'8박스', vendor:'그린패키지', unit:'박스', total:'₩196,000', count:'7건', avg:'₩14,000/박스', recent:'₩14,000/박스', rows:[['2026.08.05','그린패키지','20박스','₩14,000','₩280,000'],['2026.07.01','그린패키지','10박스','₩13,500','₩135,000'],['2026.06.04','패키지온','8박스','₩14,500','₩116,000']] },
  '쇼핑백': { category:'포장재', zone:'홀', stock:'180장', minimum:'150장', vendor:'그린패키지', unit:'장', total:'₩96,000', count:'4건', avg:'₩300/장', recent:'₩320/장', rows:[['2026.08.05','그린패키지','300장','₩320','₩96,000'],['2026.06.10','그린패키지','200장','₩290','₩58,000'],['2026.05.04','패키지온','100장','₩300','₩30,000']] }
};
const vendorDetails = {
  '푸른식자재': { total:'₩1,840,000', count:'24건', contact:'02-555-1840', zone:'주방', items:['양파','대파','감자'], dates:[['2026.08.08','6개 품목','₩248,000'],['2026.08.01','8개 품목','₩385,000'],['2026.07.25','5개 품목','₩214,000']] },
  '한성정육': { total:'₩1,250,000', count:'12건', contact:'02-555-3061', zone:'주방', items:['한우 등심','삼겹살'], dates:[['2026.08.07','4개 품목','₩415,000'],['2026.07.30','3개 품목','₩344,000'],['2026.07.18','3개 품목','₩271,000']] },
  '그린패키지': { total:'₩698,200', count:'9건', contact:'02-555-8920', zone:'홀', items:['포장용기','냅킨','쇼핑백','식용유'], dates:[['2026.08.05','8개 품목','₩89,200'],['2026.07.14','5개 품목','₩152,600'],['2026.07.01','4개 품목','₩140,000']] }
};
let selectedItem = '양파';
let selectedVendor = '푸른식자재';
let selectedReceiptId = 1;

function detailLink(label, attribute, value) { return `<button class="detail-link" data-${attribute}="${value}">${label}<span>›</span></button>`; }
function items() { const names = activeZone === 'kitchen' ? ['양파','한우 등심','식용유'] : ['포장용기','냅킨','쇼핑백']; return `<section class="zone-header"><div><p class="eyebrow">품목 관리</p><h2>${activeZone === 'kitchen' ? '주방 발주 품목' : '홀 운영 품목'}</h2><p class="muted">품목을 선택하면 날짜별 거래와 발주 금액을 확인합니다.</p></div><div class="zone-switcher" role="tablist"><button class="${activeZone === 'kitchen' ? 'selected' : ''}" data-zone="kitchen">주방</button><button class="${activeZone === 'hall' ? 'selected' : ''}" data-zone="hall">홀</button></div></section><section class="item-list">${names.map(name=>{const d=itemDetails[name];return `<article class="item-list-card"><div class="item-main"><span class="zone-label ${d.zone === '홀' ? 'hall' : 'kitchen'}">${d.zone}</span><h2>${name}</h2><p>${d.category} · 현재고 ${d.stock} · 최소 ${d.minimum}</p></div><div class="item-cost"><strong>${d.recent}</strong><small>최근 단가</small></div>${detailLink('상세 보기','item',name)}</article>`;}).join('')}</section>`; }
function vendors() { return `<section class="vendor-summary"><div><p class="eyebrow">업체별 발주</p><h2>주문한 업체와 품목</h2><p class="muted">거래처를 선택하면 날짜별 주문과 품목별 금액을 확인할 수 있습니다.</p></div><button class="secondary-button">＋ 업체 추가</button></section><section class="vendor-grid">${Object.entries(vendorDetails).map(([name,d])=>`<article class="vendor-card"><div class="vendor-card-top"><div><span class="zone-label ${d.zone === '홀' ? 'hall' : 'kitchen'}">${d.zone}</span><h2>${name}</h2></div><strong>${d.total}</strong></div><div class="vendor-meta"><span>이번 달 ${d.count} 거래</span><span>최근 8월 ${name === '푸른식자재' ? '8' : name === '한성정육' ? '7' : '5'}일</span></div><div class="vendor-items"><p>주문 품목</p>${d.items.map(i=>`<span>${i}</span>`).join('')}</div>${detailLink('거래 상세 보기','vendor',name)}</article>`).join('')}</section>`; }
function itemDetail() { const d=itemDetails[selectedItem]; return `<section class="detail-heading"><button class="back-button" data-back="items">‹ 품목 목록</button><p class="eyebrow">${d.zone} · ${d.category}</p><h2>${selectedItem}</h2><p class="muted">기본 주문 업체 ${d.vendor} · 재고 ${d.stock}</p></section><section class="detail-kpis"><article><p>이번 달 발주금액</p><strong>${d.total}</strong></article><article><p>이번 달 거래</p><strong>${d.count}</strong></article><article><p>평균 단가</p><strong>${d.avg}</strong></article><article><p>최근 단가</p><strong>${d.recent}</strong></article></section><article class="panel"><div class="panel-heading"><div><p class="eyebrow">날짜별 거래</p><h2>발주 이력</h2></div><button class="secondary-button">기간: 이번 달⌄</button></div><div class="table-wrap"><table><thead><tr><th>발주 날짜</th><th>업체</th><th>수량</th><th>단가</th><th>품목 금액</th></tr></thead><tbody>${d.rows.map(r=>`<tr><td><strong>${r[0]}</strong></td><td>${r[1]}</td><td>${r[2]}</td><td>${r[3]}</td><td><strong>${r[4]}</strong></td></tr>`).join('')}</tbody></table></div></article><section class="detail-grid"><article class="panel"><p class="eyebrow">재고 기준</p><h2>${d.stock} 보유</h2><p class="muted">최소 재고 ${d.minimum} · 일평균 사용량 기준 재고 확인이 필요합니다.</p></article><article class="panel"><p class="eyebrow">주문 업체</p><h2>${d.vendor}</h2>${detailLink('업체 거래 상세 보기','vendor',d.vendor)}</article></section>`; }
function vendorDetail() { const d=vendorDetails[selectedVendor]; return `<section class="detail-heading"><button class="back-button" data-back="vendors">‹ 업체 목록</button><p class="eyebrow">${d.zone} 거래처</p><h2>${selectedVendor}</h2><p class="muted">연락처 ${d.contact} · 주력 품목 ${d.items.join(', ')}</p></section><section class="detail-kpis"><article><p>이번 달 발주금액</p><strong>${d.total}</strong></article><article><p>이번 달 거래</p><strong>${d.count}</strong></article><article><p>최근 발주일</p><strong>${d.dates[0][0]}</strong></article><article><p>주문 품목</p><strong>${d.items.length}개</strong></article></section><article class="panel"><div class="panel-heading"><div><p class="eyebrow">날짜별 주문</p><h2>최근 거래 내역</h2></div><button class="primary-button">＋ 발주 등록</button></div><div class="table-wrap"><table><thead><tr><th>발주 날짜</th><th>거래 품목</th><th>총 금액</th><th></th></tr></thead><tbody>${d.dates.map(r=>`<tr><td><strong>${r[0]}</strong></td><td>${r[1]}</td><td><strong>${r[2]}</strong></td><td><button class="text-button" data-receipt="${r[0]}">영수증 보기 →</button></td></tr>`).join('')}</tbody></table></div></article><article class="panel vendor-product-panel"><p class="eyebrow">주문 품목별 현황</p><h2>이 업체에서 주문한 품목</h2><div class="vendor-product-links">${d.items.map(name=>itemDetails[name] ? detailLink(name,'item',name) : `<span class="product-tag">${name}</span>`).join('')}</div></article>`; }
function receiptDate(value) { return value.includes('-') ? value.replaceAll('-','.') : value; }
function receiptItems(receipt) { const byVendor = { '푸른식자재':['양파 20kg','대파 10kg','감자 15kg'], '한성정육':['한우 등심 5kg','삼겹살 10kg'], '그린패키지':['포장용기 500개','냅킨 20박스','쇼핑백 300장'] }; return receipt.items || byVendor[receipt.vendor] || ['OCR 품목 분석 대기']; }
function receipts() { const groups = state.receipts.reduce((map,r)=>{ const key=receiptDate(r.date); (map[key] ||= []).push(r); return map; },{}); return `<section class="receipt-intro"><div><p class="eyebrow">영수증 발주 기록</p><h2>날짜별 발주 품목</h2><p class="muted">사진을 올리면 해당 날짜의 업체·품목·금액을 한곳에서 확인합니다.</p></div><button class="primary-button" id="upload-button-inline">＋ 영수증 등록</button></section><section class="receipt-days">${Object.entries(groups).sort((a,b)=>b[0].localeCompare(a[0])).map(([date,list])=>`<article class="receipt-day"><div class="receipt-day-title"><div><p class="eyebrow">발주일</p><h2>${date}</h2></div><span>${list.length}건 · ${won(list.reduce((s,r)=>s+r.total,0))}</span></div>${list.map(r=>`<button class="receipt-row" data-receipt-id="${r.id}"><span class="receipt-thumb">${r.imageUrl ? `<img src="${r.imageUrl}" alt="${date} ${r.vendor} 영수증" />` : '▤'}</span><span class="receipt-row-main"><strong>${r.vendor}</strong><small>${receiptItems(r).join(' · ')}</small></span><span class="receipt-row-total"><strong>${won(r.total)}</strong>${badge(r.status)}</span><span class="chevron">›</span></button>`).join('')}</article>`).join('')}</section>`; }
function receiptDetail() { const r=state.receipts.find(receipt=>String(receipt.id)===String(selectedReceiptId)); if (!r) return `<p>영수증을 찾을 수 없습니다.</p>`; const items=receiptItems(r); const itemAmount=r.total && items.length ? Math.round(r.total/items.length) : 0; return `<section class="detail-heading"><button class="back-button" data-back="receipts">‹ 날짜별 영수증</button><p class="eyebrow">${receiptDate(r.date)} · ${r.status}</p><h2>${r.vendor} 발주</h2><p class="muted">영수증 원본과 인식된 발주 품목을 확인하세요.</p></section><section class="receipt-detail-layout"><article class="receipt-image-card">${r.imageUrl ? `<img src="${r.imageUrl}" alt="${r.vendor} 영수증 원본" />` : `<div class="receipt-placeholder"><span>▤</span><strong>영수증 원본</strong><small>사진이 연결되면 이곳에 표시됩니다.</small></div>`}</article><article class="receipt-total-card"><p>총 발주금액</p><strong>${won(r.total)}</strong><span>${items.length}개 품목 · ${r.vendor}</span></article></section><article class="panel"><div class="panel-heading"><div><p class="eyebrow">${receiptDate(r.date)} 발주 품목</p><h2>영수증 품목 내역</h2></div>${badge(r.status)}</div><div class="receipt-item-lines">${items.map((item,index)=>`<div><span><strong>${item}</strong><small>OCR 인식 품목 ${index+1}</small></span><strong>${itemAmount ? won(itemAmount) : '확인 필요'}</strong></div>`).join('')}</div></article>`; }
window.addReceiptFromUpload = function(file) { const date=document.getElementById('receipt-date').value || '2026-08-09'; const vendor=document.getElementById('receipt-vendor').value; const finish=(imageUrl)=>{ state.receipts.unshift({ id:Date.now(), vendor, date, total:0, status:'검토 필요', lines:0, imageUrl, items:['OCR 분석 중'] }); persist(); document.getElementById('receipt-dialog').close(); document.getElementById('receipt-file').value=''; document.getElementById('start-ocr').disabled=true; render('receipts'); }; if (!file.type.startsWith('image/')) { finish(''); return; } const reader=new FileReader(); reader.onload=event=>finish(event.target.result); reader.readAsDataURL(file); };
pages.itemDetail = { title:'품목 상세', render:itemDetail };
pages.vendorDetail = { title:'업체 거래 상세', render:vendorDetail };
pages.receipts.render = receipts;
pages.receiptDetail = { title:'영수증 발주 상세', render:receiptDetail };
pages.items.render = items;
pages.vendors.render = vendors;
function bindPageActions() { document.querySelectorAll('[data-go]').forEach(b => b.onclick = () => render(b.dataset.go)); document.querySelectorAll('[data-zone]').forEach(b => b.onclick = () => { activeZone = b.dataset.zone; render('items'); }); document.querySelectorAll('[data-item]').forEach(b => b.onclick = () => { selectedItem = b.dataset.item; render('itemDetail'); }); document.querySelectorAll('[data-vendor]').forEach(b => b.onclick = () => { selectedVendor = b.dataset.vendor; render('vendorDetail'); }); document.querySelectorAll('[data-receipt-id]').forEach(b => b.onclick = () => { selectedReceiptId = b.dataset.receiptId; render('receiptDetail'); }); document.querySelectorAll('[data-back]').forEach(b => b.onclick = () => render(b.dataset.back)); document.querySelectorAll('[data-usage]').forEach(b => b.onclick = () => recordUsage(b.dataset.usage)); document.querySelectorAll('[data-confirm]').forEach(b => b.onclick = () => confirmReceipt(Number(b.dataset.confirm))); document.getElementById('upload-button-inline')?.addEventListener('click', openUpload); document.getElementById('usage-button')?.addEventListener('click', () => recordUsage('양파')); }
