-- This version was already applied in the shared Supabase project.
-- Kept as a no-op locally to preserve the existing remote migration history.
-- Do not remove or reapply the remote change from this repository.
