const { database } = require('../../_lib/db');
const { currentMembership } = require('../../_lib/session');
module.exports = async (req,res) => {
  if (req.method !== 'POST') return res.status(405).end();
  const member=await currentMembership(req,['admin','manager']); if(!member) return res.status(403).json({message:'관리자 또는 매니저만 발주를 확정할 수 있습니다.'});
  const {receiptId,vendorName,receiptDate,lines=[]}=req.body||{}; if(!receiptId||!lines.length) return res.status(400).json({message:'최소 한 개 품목이 필요합니다.'});
  const client=await database().connect();
  try { await client.query('begin'); const receipt=(await client.query('select * from public.orderfit_user_receipts where id=$1 and organization_id=$2 for update',[receiptId,member.organization_id])).rows[0]; if(!receipt) throw new Error('Receipt not found'); if(receipt.status==='confirmed') throw new Error('이미 확정된 발주입니다.');
    let vendor=(await client.query('select * from public.orderfit_user_vendors where organization_id=$1 and name=$2',[member.organization_id,vendorName])).rows[0]; if(!vendor) vendor=(await client.query("insert into public.orderfit_user_vendors(organization_id,name,default_zone) values($1,$2,'shared') returning *",[member.organization_id,vendorName])).rows[0];
    await client.query('delete from public.orderfit_user_receipt_lines where receipt_id=$1',[receipt.id]); let total=0;
    for(let index=0;index<lines.length;index++){const line=lines[index]; const amount=Number(line.amount)||0, quantity=Number(line.quantity)||1; total+=amount; let item=(await client.query('select * from public.orderfit_user_items where organization_id=$1 and name=$2',[member.organization_id,line.name])).rows[0]; if(!item) item=(await client.query("insert into public.orderfit_user_items(organization_id,name,zone,base_unit,minimum_stock) values($1,$2,$3,$4,0) returning *",[member.organization_id,line.name,line.zone==='hall'?'hall':'kitchen',line.unit||'개'])).rows[0]; const saved=(await client.query('insert into public.orderfit_user_receipt_lines(receipt_id,organization_id,item_id,name,zone,quantity,unit,unit_price,amount,sort_order) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) returning *',[receipt.id,member.organization_id,item.id,line.name,line.zone==='hall'?'hall':'kitchen',quantity,line.unit||'개',amount,amount,index])).rows[0]; await client.query("insert into public.orderfit_user_inventory_transactions(organization_id,item_id,receipt_line_id,quantity_delta,created_by) values($1,$2,$3,$4,$5)",[member.organization_id,item.id,saved.id,quantity,member.user.id]); }
    await client.query("update public.orderfit_user_receipts set vendor_id=$1,vendor_name=$2,receipt_date=$3,total_amount=$4,status='confirmed',confirmed_by=$5,confirmed_at=now() where id=$6",[vendor.id,vendorName,receiptDate,total,member.user.id,receipt.id]); await client.query('commit'); return res.status(200).json({ok:true});
  } catch(error){await client.query('rollback'); console.error(error); return res.status(400).json({message:error.message||'발주 확정에 실패했습니다.'});} finally {client.release();}
};
